# Entrenamiento de redes neuronales en Python

En este ejercicio se entrena una red neuronal. Se trabajará con una base de datos de transacciones de un supermercado, con el objetivo de pronosticar el revenue de una transacción como función de distintas variables recopiladas.

Importar librerias

In [1]:
import pandas as pd
import numpy as np
from sklearn.preprocessing import StandardScaler
from sklearn.neural_network import MLPRegressor


# Información de utilidad en la implementación del método MLP

**MLPRegressor:** implementa un perceptrón multicapa (MLP) que entrena iterativamente usando la propagación hacia atrás sin función de activación en la capa de salida, que también puede verse como la función de identidad como función de activación. Por lo tanto, utiliza el error cuadrado como la función de pérdida, y la salida es un conjunto de valores continuos. MLPRegressor también admite la regresión de múltiples salidas, en la que una
muestra puede tener más de un objetivo. 

El parámetro alpha se usa como término de regularización (regularización L2) que ayuda a evitar el sobreajuste al penalizar pesos con grandes magnitudes.

Lectura de datos

In [3]:
# Leer datos de discriminación salarial
datos = pd.read_csv('Supermarket Transactions.csv')
# Visualización
datos.head()


Transaction Purchase Date  Customer ID Gender Marital Status Homeowner  \
0            1    18/12/2011         7223      F              S         Y   
1            2    20/12/2011         7841      M              M         Y   
2            3    21/12/2011         8374      F              M         N   
3            4    21/12/2011         9619      M              M         Y   
4            5    22/12/2011         1900      F              S         Y   

   Children Annual Income           City State or Province Country  \
0         2     30K - 50K    Los Angeles                CA     USA   
1         5     70K - 90K    Los Angeles                CA     USA   
2         2     50K - 70K      Bremerton                WA     USA   
3         3     30K - 50K       Portland                OR     USA   
4         3   130K - 150K  Beverly Hills                CA     USA   

  Product Family Product Department      Product Category  Units Sold  Revenue  
0           Food        Snack Foods           Snack Foods           5    27.38  
1           Food            Produce            Vegetables           5    14.90  
2           Food        Snack Foods           Snack Foods           3     5.52  
3           Food             Snacks                 Candy           4     4.44  
4          Drink          Beverages  Carbonated Beverages           4    14.00

In [5]:
# Describir los datos
datos.describe()


Transaction   Customer ID      Children    Units Sold       Revenue
count  14059.000000  14059.000000  14059.000000  14059.000000  14059.000000
mean    7030.000000   5116.902127      2.530336      4.080589     13.004512
std     4058.628052   2920.755202      1.491852      1.174421      8.215543
min        1.000000      3.000000      0.000000      1.000000      0.530000
25%     3515.500000   2549.000000      1.000000      3.000000      6.840000
50%     7030.000000   5060.000000      3.000000      4.000000     11.250000
75%    10544.500000   7633.000000      4.000000      5.000000     17.370000
max    14059.000000  10280.000000      5.000000      8.000000     56.700000

Definimos y para todos los modelos como Revenue

In [7]:
# Fijar el revenue como "y" y como un vector
y = datos['Revenue'].values
# Aplicar el comando reshape
y = y.reshape(-1, 1)
# Imprimamos y
y


array([[27.38],
       [14.9 ],
       [ 5.52],
       ...,
       [ 3.24],
       [ 4.  ],
       [25.53]])

Escalado de y

Para los modelos de aprendizaje, es ampliamente sugerido trabajar con datos en la misma escala. Usaremos StandardScaler para esto.

In [8]:
# Crear el objeto
sc_y = StandardScaler()
# Aplicar el escalado
y = sc_y.fit_transform(y)
# Ver los resultados
y


array([[ 1.74985379],
       [ 0.23072798],
       [-0.91105087],
       ...,
       [-1.18858348],
       [-1.09607261],
       [ 1.52466287]])

Modelo 1: Revenue vs. Children y Units sold

In [10]:
# Asignar variable de entrada X1X2 para entrenamiento (recuerde que ya se asignó y antes)
X1X2 = datos[['Children', 'Units Sold']]
# Imprimir X1X2
X1X2


Children  Units Sold
0             2           5
1             5           5
2             2           3
3             3           4
4             3           4
...         ...         ...
14054         2           3
14055         3           3
14056         1           4
14057         4           2
14058         3           5

[14059 rows x 2 columns]

Escalado de variables

In [11]:
# Crear el objeto
sc_X1X2 = StandardScaler()
# Aplicar el escalado
X1X2 = sc_X1X2.fit_transform(X1X2)
# Ver los resultados
X1X2


array([[-0.35550122,  0.78289131],
       [ 1.65549326,  0.78289131],
       [-0.35550122, -0.92013653],
       ...,
       [-1.02583271, -0.06862261],
       [ 0.98516177, -1.77165045],
       [ 0.31483027,  0.78289131]])

Algoritmo iterativo del modelo 1

In [12]:
# Creamos el objeto de regresión multicapa
MLR = MLPRegressor(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(3, 3))
# Entrenamos el modelo
MLR.fit(X1X2, y)
# Calculamos el score
score1 = MLR.score(X1X2, y)
# Imprimimos el score
score1

/Users/hrodriguez/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.09267000917796109

Modelo 2: Revenue vs. Children, Units Sold, Transaction y Customer ID

In [13]:
# Asignar variable de entrada X1X2X3X4 para entrenamiento, considerando Children,Units Sold,Transaction, Customer ID
X1X2X3X4 = datos[['Children', 'Units Sold', 'Transaction', 'Customer ID']]
# Imprimir X1X2X3X4
X1X2X3X4

Children  Units Sold  Transaction  Customer ID
0             2           5            1         7223
1             5           5            2         7841
2             2           3            3         8374
3             3           4            4         9619
4             3           4            5         1900
...         ...         ...          ...          ...
14054         2           3        14055         9102
14055         3           3        14056         4822
14056         1           4        14057          250
14057         4           2        14058         6153
14058         3           5        14059         3656

[14059 rows x 4 columns]

Escalado de variables

In [14]:
# Crear el objeto
sc_X1X2X3X4 = StandardScaler()
# Aplicar el escalado
X1X2X3X4 = sc_X1X2X3X4.fit_transform(X1X2X3X4)
# Ver los resultados
X1X2X3X4


array([[-0.35550122,  0.78289131, -1.73192761,  0.72110555],
       [ 1.65549326,  0.78289131, -1.73168122,  0.93270219],
       [-0.35550122, -0.92013653, -1.73143482,  1.11519573],
       ...,
       [-1.02583271, -0.06862261,  1.73143482, -1.66637561],
       [ 0.98516177, -1.77165045,  1.73168122,  0.35474891],
       [ 0.31483027,  0.78289131,  1.73192761, -0.50019738]])

Algoritmo iterativo del modelo 2

In [15]:
# Creamos el objeto de regresión multicapa
MLR = MLPRegressor(solver='lbfgs', alpha=1e-5, hidden_layer_sizes=(3, 3))
# Entrenamos el modelo
MLR.fit(X1X2X3X4, y)
# Calculamos el score
score2 = MLR.score(X1X2X3X4, y)
# Imprimimos el score
score2

/Users/hrodriguez/opt/anaconda3/lib/python3.8/site-packages/sklearn/utils/validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


0.09139611839440498